// Simplified Type Chart
export const TYPE_CHART = {
  normal: { rock: 0.5, ghost: 0, steel: 0.5 },
  fire: { fire: 0.5, water: 0.5, grass: 2, ice: 2, bug: 2, rock: 0.5, dragon: 0.5, steel: 2 },
  water: { fire: 2, water: 0.5, grass: 0.5, ground: 2, rock: 2, dragon: 0.5 },
  electric: { water: 2, electric: 0.5, grass: 0.5, ground: 0, flying: 2, dragon: 0.5 },
  grass: {
    fire: 0.5,
    water: 2,
    grass: 0.5,
    poison: 0.5,
    ground: 2,
    flying: 0.5,
    bug: 0.5,
    rock: 2,
    dragon: 0.5,
    steel: 0.5,
  },
  ice: { fire: 0.5, water: 0.5, grass: 2, ice: 0.5, ground: 2, flying: 2, dragon: 2, steel: 0.5 },
  fighting: {
    normal: 2,
    ice: 2,
    rock: 2,
    dark: 2,
    steel: 2,
    poison: 0.5,
    flying: 0.5,
    psychic: 0.5,
    bug: 0.5,
    ghost: 0,
    fairy: 0.5,
  },
  poison: { grass: 2, poison: 0.5, ground: 0.5, rock: 0.5, ghost: 0.5, steel: 0, fairy: 2 },
  ground: { fire: 2, electric: 2, grass: 0.5, poison: 2, flying: 0, bug: 0.5, rock: 2, steel: 2 },
  flying: { electric: 0.5, grass: 2, fighting: 2, bug: 2, rock: 0.5, steel: 0.5 },
  psychic: { fighting: 2, poison: 2, psychic: 0.5, dark: 0, steel: 0.5 },
  bug: {
    fire: 0.5,
    grass: 2,
    fighting: 0.5,
    poison: 0.5,
    flying: 0.5,
    psychic: 2,
    ghost: 0.5,
    dark: 2,
    steel: 0.5,
    fairy: 0.5,
  },
  rock: { fire: 2, ice: 2, fighting: 0.5, ground: 0.5, flying: 2, bug: 2, steel: 0.5 },
  ghost: { normal: 0, psychic: 2, ghost: 2, dark: 0.5 },
  dragon: { dragon: 2, steel: 0.5, fairy: 0 },
  steel: { fire: 0.5, water: 0.5, electric: 0.5, ice: 2, rock: 2, fairy: 2, steel: 0.5 },
  fairy: { fire: 0.5, fighting: 2, poison: 0.5, dragon: 2, dark: 2, steel: 0.5 },
};

export const TYPE_COLORS = {
  fire: '#ef4444',
  grass: '#22c55e',
  water: '#3b82f6',
  electric: '#eab308',
  psychic: '#a855f7',
  rock: '#78350f',
  ground: '#78350f',
  ice: '#67e8f9',
  dragon: '#6366f1',
  dark: '#1e293b',
  fairy: '#f472b6',
  fighting: '#ea580c',
  poison: '#9333ea',
  bug: '#65a30d',
  ghost: '#4c1d95',
  steel: '#94a3b8',
};

export const MOVE_POOL = {
  normal: [
    { name: 'Tackle', type: 'normal', power: 40, accuracy: 100, cost: 1 },
    { name: 'Scratch', type: 'normal', power: 40, accuracy: 100, cost: 1 },
    { name: 'Quick Attack', type: 'normal', power: 40, accuracy: 100, cost: 1 },
    { name: 'Slam', type: 'normal', power: 80, accuracy: 75, cost: 3 },
    { name: 'Hyper Beam', type: 'normal', power: 150, accuracy: 90, cost: 4, recoil: 0.5 },
  ],
  fire: [
    {
      name: 'Ember',
      type: 'fire',
      power: 40,
      accuracy: 100,
      cost: 1,
      status: 'burn',
      statusChance: 0.1,
    },
    {
      name: 'Flame Wheel',
      type: 'fire',
      power: 60,
      accuracy: 100,
      cost: 2,
      status: 'burn',
      statusChance: 0.1,
    },
    {
      name: 'Flamethrower',
      type: 'fire',
      power: 90,
      accuracy: 100,
      cost: 3,
      status: 'burn',
      statusChance: 0.1,
    },
    {
      name: 'Fire Blast',
      type: 'fire',
      power: 110,
      accuracy: 85,
      cost: 4,
      recoil: 0.2,
      status: 'burn',
      statusChance: 0.3,
    },
  ],
  water: [
    { name: 'Water Gun', type: 'water', power: 40, accuracy: 100, cost: 1 },
    {
      name: 'Bubble Beam',
      type: 'water',
      power: 65,
      accuracy: 100,
      cost: 2,
      status: 'speed_down',
      statusChance: 0.1,
    },
    { name: 'Surf', type: 'water', power: 90, accuracy: 100, cost: 3 },
    { name: 'Hydro Pump', type: 'water', power: 110, accuracy: 80, cost: 4, recoil: 0.2 },
  ],
  grass: [
    { name: 'Vine Whip', type: 'grass', power: 45, accuracy: 100, cost: 1 },
    { name: 'Razor Leaf', type: 'grass', power: 55, accuracy: 95, cost: 2 },
    { name: 'Solar Beam', type: 'grass', power: 120, accuracy: 100, cost: 4, recoil: 0.3 },
    {
      name: 'Sleep Powder',
      type: 'grass',
      power: 0,
      accuracy: 75,
      cost: 2,
      status: 'sleep',
      statusChance: 1.0,
    },
  ],
  electric: [
    {
      name: 'Thundershock',
      type: 'electric',
      power: 40,
      accuracy: 100,
      cost: 1,
      status: 'paralysis',
      statusChance: 0.1,
    },
    {
      name: 'Thunderbolt',
      type: 'electric',
      power: 90,
      accuracy: 100,
      cost: 3,
      status: 'paralysis',
      statusChance: 0.1,
    },
    {
      name: 'Thunder',
      type: 'electric',
      power: 110,
      accuracy: 70,
      cost: 4,
      recoil: 0.2,
      status: 'paralysis',
      statusChance: 0.3,
    },
  ],
  ice: [
    {
      name: 'Powder Snow',
      type: 'ice',
      power: 40,
      accuracy: 100,
      cost: 1,
      status: 'freeze',
      statusChance: 0.1,
    },
    {
      name: 'Ice Beam',
      type: 'ice',
      power: 90,
      accuracy: 100,
      cost: 3,
      status: 'freeze',
      statusChance: 0.1,
    },
    {
      name: 'Blizzard',
      type: 'ice',
      power: 110,
      accuracy: 70,
      cost: 4,
      status: 'freeze',
      statusChance: 0.3,
    },
  ],
  fighting: [
    { name: 'Karate Chop', type: 'fighting', power: 50, accuracy: 100, cost: 1 },
    { name: 'Brick Break', type: 'fighting', power: 75, accuracy: 100, cost: 2 },
    { name: 'Close Combat', type: 'fighting', power: 120, accuracy: 100, cost: 4, recoil: 0.3 },
  ],
  poison: [
    {
      name: 'Poison Sting',
      type: 'poison',
      power: 15,
      accuracy: 100,
      cost: 1,
      status: 'poison',
      statusChance: 0.3,
    },
    {
      name: 'Sludge Bomb',
      type: 'poison',
      power: 90,
      accuracy: 100,
      cost: 3,
      status: 'poison',
      statusChance: 0.3,
    },
    {
      name: 'Gunk Shot',
      type: 'poison',
      power: 120,
      accuracy: 80,
      cost: 4,
      status: 'poison',
      statusChance: 0.3,
    },
  ],
  ground: [
    { name: 'Mud Slap', type: 'ground', power: 20, accuracy: 100, cost: 1 },
    { name: 'Earthquake', type: 'ground', power: 100, accuracy: 100, cost: 3 },
    { name: 'Earth Power', type: 'ground', power: 90, accuracy: 100, cost: 3 },
  ],
  flying: [
    { name: 'Peck', type: 'flying', power: 35, accuracy: 100, cost: 1 },
    { name: 'Aerial Ace', type: 'flying', power: 60, accuracy: 100, cost: 2 },
    { name: 'Brave Bird', type: 'flying', power: 120, accuracy: 100, cost: 4, recoil: 0.3 },
  ],
  psychic: [
    { name: 'Confusion', type: 'psychic', power: 50, accuracy: 100, cost: 1 },
    { name: 'Psybeam', type: 'psychic', power: 65, accuracy: 100, cost: 2 },
    { name: 'Psychic', type: 'psychic', power: 90, accuracy: 100, cost: 3 },
  ],
  bug: [
    { name: 'Bug Bite', type: 'bug', power: 60, accuracy: 100, cost: 1 },
    { name: 'Signal Beam', type: 'bug', power: 75, accuracy: 100, cost: 2 },
    { name: 'X-Scissor', type: 'bug', power: 80, accuracy: 100, cost: 3 },
  ],
  rock: [
    { name: 'Rock Throw', type: 'rock', power: 50, accuracy: 90, cost: 1 },
    { name: 'Rock Slide', type: 'rock', power: 75, accuracy: 90, cost: 2 },
    { name: 'Stone Edge', type: 'rock', power: 100, accuracy: 80, cost: 3 },
  ],
  ghost: [
    { name: 'Lick', type: 'ghost', power: 30, accuracy: 100, cost: 1 },
    { name: 'Shadow Ball', type: 'ghost', power: 80, accuracy: 100, cost: 3 },
    { name: 'Shadow Claw', type: 'ghost', power: 70, accuracy: 100, cost: 2 },
  ],
  dragon: [
    { name: 'Dragon Breath', type: 'dragon', power: 60, accuracy: 100, cost: 2 },
    { name: 'Dragon Claw', type: 'dragon', power: 80, accuracy: 100, cost: 3 },
    { name: 'Outrage', type: 'dragon', power: 120, accuracy: 100, cost: 4, recoil: 0.3 },
  ],
  steel: [
    { name: 'Metal Claw', type: 'steel', power: 50, accuracy: 95, cost: 1 },
    { name: 'Iron Head', type: 'steel', power: 80, accuracy: 100, cost: 3 },
    { name: 'Flash Cannon', type: 'steel', power: 80, accuracy: 100, cost: 3 },
  ],
  fairy: [
    { name: 'Fairy Wind', type: 'fairy', power: 40, accuracy: 100, cost: 1 },
    { name: 'Dazzling Gleam', type: 'fairy', power: 80, accuracy: 100, cost: 3 },
    { name: 'Moonblast', type: 'fairy', power: 95, accuracy: 100, cost: 3 },
  ],
};

export const DEFAULT_MOVES = [
  { name: 'Tackle', type: 'normal', power: 40, accuracy: 100, cost: 1 },
  { name: 'Leer', type: 'normal', power: 0, accuracy: 100, cost: 1 }, // Placeholder for non-damaging
];
