export const typeTranslations = {
  normal: 'Normaal',
  fire: 'Vuur',
  water: 'Water',
  grass: 'Gras',
  electric: 'Elektrisch',
  ice: 'IJs',
  fighting: 'Vecht',
  poison: 'Gif',
  ground: 'Grond',
  flying: 'Vlieg',
  psychic: 'Psychisch',
  bug: 'Insect',
  rock: 'Steen',
  ghost: 'Geest',
  dragon: 'Draak',
  steel: 'Staal',
  dark: 'Duister',
  fairy: 'Fee'
};
